version: '3'

services:
  app:
    container_name: api-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    networks:
      - api-boilerplate
networks:
  api-boilerplate:
    driver: bridge
